### PR TITLE
Database

### PR DESCRIPTION
**Pull request by asimzz**

### CODE REVIEW

**Comment by princeemensah** [comment]
Great! I'll check them out.

**Comment by princeemensah** [comment]
I have checked it out, I think it's cool to merge. Also, can you try dropping the other pipeline with the lstm model. The current one with transformer(bert model) is inside the src directory. It looks great and cool!

**Comment by asimzz** [comment]
> I have checked it out, I think it's cool to merge. Also, can you try dropping the other pipeline with the lstm model. The current one with transformer(bert model) is inside the src directory. It looks great and cool!

I think you are replaying in the wrong PR. However, let me test both branches mine and your locally to see if we gonna have some conflicts or not.

**Comment by princeemensah** [comment]
Yes, I just realized. It's okay but I don't think there'll be conflict.

**Pull request merged**
